# This file configures how Netlify builds and deploys your site.

[build]
  # This command tells Netlify to first install the necessary dependencies (like firebase-admin)
  # from your package.json, and then run the 'build' script which executes build.js.
  command = "npm install && npm run build"
  
  # This tells Netlify which folder contains the final, generated website to make public.
  # Your build.js script is configured to place all the static files into this 'dist' folder.
  publish = "dist"

